[project]
name = "local-codebase-analyst"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=3.0.0b1",
    "ipykernel>=7.1.0",
    "langchain>=1.2.8",
    "langchain-groq>=1.1.2",
]
